version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sequelize
    versions:
    - "> 5.13.1"
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: enmap
    versions:
    - 5.8.4
  - dependency-name: sqlite3
    versions:
    - 5.0.1
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
